import = ["~/.config/i3/alacritty/colors.toml", "~/.config/i3/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"

[window]
decorations = "full"

[scrolling]
history = 10000
multiplier = 3

[window.dimensions]
columns = 82
lines = 25

[window.padding]
x = 12
y = 12
